substitutions:
  name: "ap33772-board-template"
  friendly_name: "AP33772 Board Template"

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: true

  project:
    name: caralyh.ap33772-board-template
    version: "1.0"

logger:
api:
ota:

# fix for logger from luar123
external_components:
  - source: github://luar123/esphome@fix_logger
    components: [logger]
    refresh: never

dashboard_import:
  package_import_url: github://caralyh/esphome/templates/ap33772-template.yaml@ap33772
  import_full_config: true

esp32_improv:
  authorizer: none
improv_serial:

wifi:
  ap: {}

captive_portal:

esp32:
  board: esp32-c6-devkitc-1
  flash_size: 8MB
  variant: esp32c6
  framework:
    type: esp-idf
    version: "5.2.1"
    platform_version: 6.6.0
    sdkconfig_options:
      CONFIG_OPENTHREAD_ENABLED: n
      CONFIG_ENABLE_WIFI_STATION: y
      CONFIG_USE_MINIMAL_MDNS: y
      CONFIG_ESPTOOLPY_FLASHSIZE_8MB: y
